apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-nfs-pv-demo
  labels:
    app.kubernetes.io/name: nfs-static-pv-demo
    storage-type: nfs-static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=4.1
  claimRef:
    namespace: nfs-static-pv-demo
    name: static-nfs-pvc-demo
  nfs:
    # Altere apenas estes campos para simular a troca do servidor NFS via Git.
    server: 10.0.0.10
    path: /exports/ocp-static-nfs-pv-demo
